;;; Elfeed score file                                     -*- lisp -*-
;;; How much I give a shit points
((version 10)
 ("title")
 ("content")
 ("title-or-content"
  ;; CRITICAL - Immediate attention
  (:text "judas release" :title-value 2000 :content-value 2000 :type W)
  (:text "bioshock release" :title-value 2000 :content-value 2000 :type W)
  (:text "ghost story games" :title-value 1500 :content-value 1500 :type W)
  (:text "gta vi release" :title-value 2000 :content-value 2000 :type W)
  (:text "elder scrolls vi" :title-value 1500 :content-value 1500 :type W)
  (:text "half-life 3" :title-value 1500 :content-value 1500 :type W)
  
  ;; HIGH PRIORITY - Gaming (Immersive Sims)
  (:text "judas" :title-value 1000 :content-value 1000 :type W)
  (:text "immersive sim" :title-value 800 :content-value 800 :type W)
  (:text "system shock" :title-value 700 :content-value 700 :type W)
  (:text "prey" :title-value 600 :content-value 600 :type W)
  (:text "dishonored" :title-value 600 :content-value 600 :type W)
  (:text "deus ex" :title-value 600 :content-value 600 :type W)
  (:text "thief" :title-value 500 :content-value 500 :type W)
  (:text "arkane studios" :title-value 700 :content-value 700 :type W)
  (:text "looking glass studios" :title-value 600 :content-value 600 :type W)
  (:text "0451" :title-value 400 :content-value 400 :type W)
  (:text "emergent gameplay" :title-value 300 :content-value 300 :type W)
  (:text "player agency" :title-value 300 :content-value 300 :type W)
  
  ;; HIGH PRIORITY - Gaming (Other)
  (:text "death stranding 2" :title-value 600 :content-value 600 :type W)
  (:text "monster hunter wilds" :title-value 500 :content-value 500 :type W)
  (:text "ghost of yotei" :title-value 500 :content-value 500 :type W)
  (:text "fallout" :title-value 400 :content-value 400 :type W)
  (:text "call of duty" :title-value 300 :content-value 300 :type W)
  (:text "bioshock" :title-value 400 :content-value 400 :type s)
  (:text "doom" :title-value 400 :content-value 400 :type W)
  (:text "media molecule" :title-value 400 :content-value 400 :type W)
  (:text "metroidvania" :title-value 300 :content-value 300 :type W)
  (:text "soulslike" :title-value 300 :content-value 300 :type W)
  (:text "roguelike" :title-value 250 :content-value 250 :type W)
  
  ;; HIGH PRIORITY - AI & Tech
  (:text "claude 4" :title-value 800 :content-value 800 :type W)
  (:text "claude code" :title-value 700 :content-value 700 :type W)
  (:text "gpt-5" :title-value 600 :content-value 600 :type W)
  (:text "o3" :title-value 500 :content-value 500 :type W)
  (:text "artificial general intelligence" :title-value 500 :content-value 500 :type W)
  (:text "agi breakthrough" :title-value 700 :content-value 700 :type W)
  (:text "reasoning models" :title-value 400 :content-value 400 :type W)
  (:text "chain of thought" :title-value 300 :content-value 300 :type W)
  (:text "context window" :title-value 250 :content-value 250 :type W)
  (:text "multimodal" :title-value 300 :content-value 300 :type W)
  (:text "constitutional ai" :title-value 300 :content-value 300 :type W)
  (:text "computer use" :title-value 400 :content-value 400 :type W)
  (:text "ai regulation" :title-value 400 :content-value 400 :type W)
  
  ;; HIGH PRIORITY - Dev Tech
  (:text "local-first" :title-value 300 :content-value 300 :type W)
  (:text "wasm" :title-value 200 :content-value 200 :type W)
  (:text "rust adoption" :title-value 200 :content-value 200 :type W)
  (:text "crdt" :title-value 250 :content-value 250 :type W)
  (:text "federated" :title-value 200 :content-value 200 :type W)
  (:text "peer-to-peer" :title-value 200 :content-value 200 :type W)
  (:text "self-sovereign" :title-value 200 :content-value 200 :type W)
  (:text "atproto" :title-value 200 :content-value 200 :type W)
  
  ;; HIGH PRIORITY - Dev Tools (Emacs)
  (:text "magit release" :title-value 400 :content-value 400 :type W)
  (:text "emacs 30" :title-value 300 :content-value 300 :type W)
  (:text "org-mode" :title-value 250 :content-value 250 :type W)
  (:text "lsp" :title-value 200 :content-value 200 :type W)
  (:text "language server" :title-value 200 :content-value 200 :type W)
  (:text "tree-sitter" :title-value 200 :content-value 200 :type W)
  (:text "nixos" :title-value 150 :content-value 150 :type W)
  (:text "doom emacs" :title-value 150 :content-value 150 :type W)
  
  ;; MEDIUM PRIORITY - Local (Halifax/NS/Atlantic)
  (:text "halifax housing crisis" :title-value 400 :content-value 400 :type W)
  (:text "halifax transit" :title-value 300 :content-value 300 :type W)
  (:text "rapid transit" :title-value 300 :content-value 300 :type W)
  (:text "ferry service" :title-value 250 :content-value 250 :type W)
  (:text "healthcare wait times" :title-value 300 :content-value 300 :type W)
  (:text "hrm" :title-value 200 :content-value 200 :type W)
  (:text "dartmouth" :title-value 150 :content-value 150 :type s)
  (:text "atlantic canada" :title-value 150 :content-value 150 :type W)
  (:text "maritime provinces" :title-value 100 :content-value 100 :type W)
  (:text "housing" :title-value 200 :content-value 200 :type W)
  (:text "healthcare" :title-value 200 :content-value 200 :type W)
  (:text "education" :title-value 250 :content-value 250 :type W)
  (:text "child care" :title-value 150 :content-value 150 :type W)
  (:text "halifax" :title-value 99 :content-value 99 :type s)
  (:text "nova scotia" :title-value 99 :content-value 99 :type s)
  
  ;; MEDIUM PRIORITY - Space
  (:text "starship launch" :title-value 400 :content-value 400 :type W)
  (:text "mars mission" :title-value 350 :content-value 350 :type W)
  (:text "artemis" :title-value 300 :content-value 300 :type W)
  
  ;; LOW PRIORITY - General topics
  (:text "javascript" :title-value 99 :content-value 99 :type s)
  (:text "climate change" :title-value 100 :content-value 100 :type W)
  (:text "emissions targets" :title-value 50 :content-value 50 :type W)
  
  ;; BONUS POINTS - Tone/Quality
  (:text "positive" :title-value 50 :content-value 50 :type W)
  (:text "motivational" :title-value 50 :content-value 50 :type W)
  (:text "inspiring" :title-value 50 :content-value 50 :type W)
  (:text "hopeful" :title-value 50 :content-value 50 :type W)
  (:text "breakthrough" :title-value 75 :content-value 75 :type W)
  
  ;; BONUS POINTS - Tech concepts
  (:text "interoperability" :title-value 50 :content-value 50 :type W)
  (:text "zero-knowledge proofs" :title-value 50 :content-value 50 :type W)
  (:text "decentralized identity" :title-value 50 :content-value 50 :type W)
  (:text "decentralized governance" :title-value 50 :content-value 50 :type W)
  
  ;; FILTER OUT - Culture wars
  (:text "culture wars" :title-value -1000 :content-value -1000 :type W)
  (:text "outrage" :title-value -500 :content-value -500 :type W)
  
  ;; FILTER OUT - Clickbait
  (:text "slammed" :title-value -300 :content-value -300 :type W)
  (:text "destroys" :title-value -300 :content-value -300 :type W)
  (:text "you won't believe" :title-value -400 :content-value -400 :type W)
  (:text "shocking" :title-value -300 :content-value -300 :type W)
  (:text "mind-blowing" :title-value -300 :content-value -300 :type W)
  (:text "game-changer" :title-value -200 :content-value -200 :type W)
  (:text "twitter meltdown" :title-value -400 :content-value -400 :type W)
  (:text "goes viral" :title-value -300 :content-value -300 :type W)
  )
 ("tag")
 ("authors"
  (:text "Ken Levine" :value 2000 :type s)
  (:text "Warren Spector" :value 1500 :type s)
  (:text "Harvey Smith" :value 1500 :type s)
  (:text "Hideo Kojima" :value 1000 :type s)
  (:text "Adam Sinicki" :value 800 :type s)
  (:text "Bioneer" :value 800 :type s)
  (:text "thebioneer" :value 800 :type s)
  (:text "The Bioneer" :value 800 :type s))
 ("feed"
  (:text "Hyperledger" :value 1 :type S :attr t)
  (:text "Nova Scotia News" :value 2 :type W :attr t)
  )
 ("adjust-tags"))
