;;; Elfeed score file                                     -*- lisp -*-
;;; How much I give a shit points
;;; Elfeed score file                                     -*- lisp -*-
;;; How much I give a shit points
;;; Elfeed score file                                     -*- lisp -*-
;;; How much I give a shit points
;;; Elfeed score file                                     -*- lisp -*-
;;; How much I give a shit points
((version 10)
 ("title")
 ("content")
 ("title-or-content"
  ;; CRITICAL - Immediate attention
  (:text "judas release" :title-value 2000 :content-value 2000 :type W)
  (:text "bioshock release" :title-value 2000 :content-value 2000 :type W)
  (:text "ghost story games" :title-value 1500 :content-value 1500 :type W)
  (:text "gta vi release" :title-value 2000 :content-value 2000 :type W)
  (:text "elder scrolls vi" :title-value 1500 :content-value 1500 :type W)
  (:text "half-life 3" :title-value 1500 :content-value 1500 :type W)
  
  ;; HIGH PRIORITY - Gaming (Immersive Sims)
  (:text "judas" :title-value 1000 :content-value 1000 :type W)
  (:text "immersive sim" :title-value 800 :content-value 800 :type W)
  (:text "system shock" :title-value 700 :content-value 700 :type W)
  (:text "prey" :title-value 600 :content-value 600 :type W)
  (:text "dishonored" :title-value 600 :content-value 600 :type W)
  (:text "deus ex" :title-value 600 :content-value 600 :type W)
  (:text "thief" :title-value 500 :content-value 500 :type W)
  (:text "arkane studios" :title-value 700 :content-value 700 :type W)
  (:text "looking glass studios" :title-value 600 :content-value 600 :type W)
  (:text "0451" :title-value 400 :content-value 400 :type W)
  (:text "emergent gameplay" :title-value 300 :content-value 300 :type W)
  (:text "player agency" :title-value 300 :content-value 300 :type W)
  
  ;; HIGH PRIORITY - Gaming (Other)
  (:text "death stranding 2" :title-value 600 :content-value 600 :type W)
  (:text "monster hunter wilds" :title-value 500 :content-value 500 :type W)
  (:text "ghost of yotei" :title-value 500 :content-value 500 :type W)
  (:text "fallout" :title-value 400 :content-value 400 :type W)
  (:text "call of duty" :title-value 300 :content-value 300 :type W)
  (:text "bioshock" :title-value 400 :content-value 400 :type s)
  (:text "doom" :title-value 400 :content-value 400 :type W)
  (:text "media molecule" :title-value 400 :content-value 400 :type W)
  (:text "metroidvania" :title-value 300 :content-value 300 :type W)
  (:text "soulslike" :title-value 300 :content-value 300 :type W)
  (:text "roguelike" :title-value 250 :content-value 250 :type W)
  
  ;; HIGH PRIORITY - AI & Tech
  (:text "claude 4" :title-value 800 :content-value 800 :type W)
  (:text "claude code" :title-value 700 :content-value 700 :type W)
  (:text "gpt-5" :title-value 600 :content-value 600 :type W)
  (:text "o3" :title-value 500 :content-value 500 :type W)
  (:text "artificial general intelligence" :title-value 500 :content-value 500 :type W)
  (:text "agi breakthrough" :title-value 700 :content-value 700 :type W)
  (:text "reasoning models" :title-value 400 :content-value 400 :type W)
  (:text "chain of thought" :title-value 300 :content-value 300 :type W)
  (:text "context window" :title-value 250 :content-value 250 :type W)
  (:text "multimodal" :title-value 300 :content-value 300 :type W)
  (:text "constitutional ai" :title-value 300 :content-value 300 :type W)
  (:text "computer use" :title-value 400 :content-value 400 :type W)
  (:text "ai regulation" :title-value 400 :content-value 400 :type W)
  
  ;; HIGH PRIORITY - VR/AR Innovation
  (:text "vision pro" :title-value 600 :content-value 600 :type W)
  (:text "quest 3" :title-value 500 :content-value 500 :type W)
  (:text "quest pro" :title-value 400 :content-value 400 :type W)
  (:text "psvr2" :title-value 400 :content-value 400 :type W)
  (:text "valve index" :title-value 400 :content-value 400 :type W)
  (:text "mixed reality" :title-value 500 :content-value 500 :type W)
  (:text "spatial computing" :title-value 500 :content-value 500 :type W)
  (:text "passthrough" :title-value 300 :content-value 300 :type W)
  (:text "eye tracking" :title-value 350 :content-value 350 :type W)
  (:text "foveated rendering" :title-value 300 :content-value 300 :type W)
  (:text "haptic feedback" :title-value 250 :content-value 250 :type W)
  (:text "hand tracking" :title-value 300 :content-value 300 :type W)
  (:text "standalone vr" :title-value 250 :content-value 250 :type W)
  (:text "pancake lenses" :title-value 200 :content-value 200 :type W)
  (:text "varifocal" :title-value 250 :content-value 250 :type W)
  (:text "retinal projection" :title-value 300 :content-value 300 :type W)
  
  ;; HIGH PRIORITY - Dev Tech
  (:text "local-first" :title-value 300 :content-value 300 :type W)
  (:text "wasm" :title-value 200 :content-value 200 :type W)
  (:text "rust adoption" :title-value 200 :content-value 200 :type W)
  (:text "crdt" :title-value 250 :content-value 250 :type W)
  (:text "federated" :title-value 200 :content-value 200 :type W)
  (:text "peer-to-peer" :title-value 200 :content-value 200 :type W)
  (:text "self-sovereign" :title-value 200 :content-value 200 :type W)
  (:text "atproto" :title-value 200 :content-value 200 :type W)
  
  ;; HIGH PRIORITY - React Development
  (:text "react 19" :title-value 400 :content-value 400 :type W)
  (:text "react server components" :title-value 400 :content-value 400 :type W)
  (:text "server components" :title-value 350 :content-value 350 :type W)
  (:text "next.js" :title-value 300 :content-value 300 :type W)
  (:text "remix" :title-value 300 :content-value 300 :type W)
  (:text "react compiler" :title-value 300 :content-value 300 :type W)
  (:text "suspense" :title-value 250 :content-value 250 :type W)
  (:text "concurrent react" :title-value 250 :content-value 250 :type W)
  (:text "vite" :title-value 200 :content-value 200 :type W)
  (:text "turbopack" :title-value 200 :content-value 200 :type W)
  (:text "tailwind" :title-value 150 :content-value 150 :type W)
  (:text "shadcn" :title-value 150 :content-value 150 :type W)
  
  ;; HIGH PRIORITY - Rails Development
  (:text "rails 8" :title-value 400 :content-value 400 :type W)
  (:text "rails 7" :title-value 300 :content-value 300 :type W)
  (:text "hotwire" :title-value 300 :content-value 300 :type W)
  (:text "turbo" :title-value 250 :content-value 250 :type W)
  (:text "stimulus" :title-value 250 :content-value 250 :type W)
  (:text "kamal" :title-value 250 :content-value 250 :type W)
  (:text "solid queue" :title-value 200 :content-value 200 :type W)
  (:text "solid cache" :title-value 200 :content-value 200 :type W)
  (:text "propshaft" :title-value 150 :content-value 150 :type W)
  (:text "importmap" :title-value 150 :content-value 150 :type W)
  (:text "activerecord" :title-value 150 :content-value 150 :type W)
  (:text "action cable" :title-value 150 :content-value 150 :type W)
  
  ;; HIGH PRIORITY - Dev Tools (Emacs)
  (:text "magit release" :title-value 400 :content-value 400 :type W)
  (:text "emacs 30" :title-value 300 :content-value 300 :type W)
  (:text "emacs 31" :title-value 300 :content-value 300 :type W)
  (:text "org-mode" :title-value 250 :content-value 250 :type W)
  (:text "org-roam" :title-value 200 :content-value 200 :type W)
  (:text "denote" :title-value 200 :content-value 200 :type W)
  (:text "lsp" :title-value 200 :content-value 200 :type W)
  (:text "language server" :title-value 200 :content-value 200 :type W)
  (:text "eglot" :title-value 200 :content-value 200 :type W)
  (:text "tree-sitter" :title-value 200 :content-value 200 :type W)
  (:text "native compilation" :title-value 200 :content-value 200 :type W)
  (:text "nixos" :title-value 150 :content-value 150 :type W)
  (:text "doom emacs" :title-value 150 :content-value 150 :type W)
  (:text "spacemacs" :title-value 150 :content-value 150 :type W)
  (:text "elpaca" :title-value 150 :content-value 150 :type W)
  (:text "straight.el" :title-value 150 :content-value 150 :type W)
  (:text "use-package" :title-value 150 :content-value 150 :type W)
  (:text "corfu" :title-value 150 :content-value 150 :type W)
  (:text "vertico" :title-value 150 :content-value 150 :type W)
  (:text "consult" :title-value 150 :content-value 150 :type W)
  (:text "embark" :title-value 150 :content-value 150 :type W)
  (:text "pgtk" :title-value 150 :content-value 150 :type W)
  
  ;; MEDIUM PRIORITY - Local (Halifax/NS/Atlantic)
  (:text "halifax housing crisis" :title-value 400 :content-value 400 :type W)
  (:text "halifax transit" :title-value 300 :content-value 300 :type W)
  (:text "rapid transit" :title-value 300 :content-value 300 :type W)
  (:text "ferry service" :title-value 250 :content-value 250 :type W)
  (:text "healthcare wait times" :title-value 300 :content-value 300 :type W)
  (:text "hrm" :title-value 200 :content-value 200 :type W)
  (:text "dartmouth" :title-value 150 :content-value 150 :type s)
  (:text "atlantic canada" :title-value 150 :content-value 150 :type W)
  (:text "maritime provinces" :title-value 100 :content-value 100 :type W)
  (:text "housing" :title-value 200 :content-value 200 :type W)
  (:text "healthcare" :title-value 200 :content-value 200 :type W)
  (:text "education" :title-value 250 :content-value 250 :type W)
  (:text "child care" :title-value 150 :content-value 150 :type W)
  (:text "halifax" :title-value 99 :content-value 99 :type s)
  (:text "nova scotia" :title-value 99 :content-value 99 :type s)
  
  ;; MEDIUM PRIORITY - Space
  (:text "starship launch" :title-value 400 :content-value 400 :type W)
  (:text "mars mission" :title-value 350 :content-value 350 :type W)
  (:text "artemis" :title-value 300 :content-value 300 :type W)
  
  ;; LOW PRIORITY - General topics
  (:text "javascript" :title-value 99 :content-value 99 :type s)
  (:text "climate change" :title-value 100 :content-value 100 :type W)
  (:text "emissions targets" :title-value 50 :content-value 50 :type W)
  
  ;; BONUS POINTS - Tone/Quality
  (:text "positive" :title-value 50 :content-value 50 :type W)
  (:text "motivational" :title-value 50 :content-value 50 :type W)
  (:text "inspiring" :title-value 50 :content-value 50 :type W)
  (:text "hopeful" :title-value 50 :content-value 50 :type W)
  (:text "breakthrough" :title-value 75 :content-value 75 :type W)
  
  ;; BONUS POINTS - Tech concepts
  (:text "interoperability" :title-value 50 :content-value 50 :type W)
  (:text "zero-knowledge proofs" :title-value 50 :content-value 50 :type W)
  (:text "decentralized identity" :title-value 50 :content-value 50 :type W)
  (:text "decentralized governance" :title-value 50 :content-value 50 :type W)
  
  ;; FILTER OUT - Culture wars
  (:text "culture wars" :title-value -1000 :content-value -1000 :type W)
  (:text "outrage" :title-value -500 :content-value -500 :type W)
  
  ;; FILTER OUT - Clickbait
  (:text "slammed" :title-value -300 :content-value -300 :type W)
  (:text "destroys" :title-value -300 :content-value -300 :type W)
  (:text "you won't believe" :title-value -400 :content-value -400 :type W)
  (:text "shocking" :title-value -300 :content-value -300 :type W)
  (:text "mind-blowing" :title-value -300 :content-value -300 :type W)
  (:text "game-changer" :title-value -200 :content-value -200 :type W)
  (:text "twitter meltdown" :title-value -400 :content-value -400 :type W)
  (:text "goes viral" :title-value -300 :content-value -300 :type W)
  
  ;; FILTER OUT - Consumer electronics noise
  (:text "iphone" :title-value -200 :content-value -200 :type W)
  (:text "galaxy s" :title-value -200 :content-value -200 :type W)
  (:text "pixel phone" :title-value -200 :content-value -200 :type W)
  (:text "unboxing" :title-value -300 :content-value -300 :type W)
  (:text "hands-on" :title-value -150 :content-value -150 :type W)
  (:text "first impressions" :title-value -150 :content-value -150 :type W)
  (:text "camera comparison" :title-value -200 :content-value -200 :type W)
  (:text "battery life test" :title-value -200 :content-value -200 :type W)
  (:text "benchmark" :title-value -150 :content-value -150 :type W)
  (:text "spec sheet" :title-value -200 :content-value -200 :type W)
  
  ;; FILTER OUT - Crime/tabloid news
  (:text "murder case" :title-value -400 :content-value -400 :type W)
  (:text "mass shooting" :title-value -400 :content-value -400 :type W)
  (:text "serial killer" :title-value -400 :content-value -400 :type W)
  (:text "manhunt" :title-value -300 :content-value -300 :type W)
  (:text "suspect arrested" :title-value -300 :content-value -300 :type W)
  (:text "breaking:" :title-value -200 :content-value -200 :type W)
  (:text "developing story" :title-value -200 :content-value -200 :type W)
  (:text "celebrity" :title-value -300 :content-value -300 :type W)
  (:text "scandal" :title-value -300 :content-value -300 :type W)
  (:text "drama" :title-value -200 :content-value -200 :type W)
  (:text "feud" :title-value -300 :content-value -300 :type W)
  (:text "controversy" :title-value -200 :content-value -200 :type W)
  (:text "accused of" :title-value -250 :content-value -250 :type W)
  (:text "alleged" :title-value -200 :content-value -200 :type W)
  )
 ("tag")
 ("authors"
  (:text "Ken Levine" :value 2000 :type s)
  (:text "Warren Spector" :value 1500 :type s)
  (:text "Harvey Smith" :value 1500 :type s)
  (:text "Hideo Kojima" :value 1000 :type s))
 ("feed"
  (:text "Hyperledger" :value 1 :type S :attr t)
  (:text "Nova Scotia News" :value 2 :type W :attr t)
  )
 ("adjust-tags"))
