;;; Elfeed score file                                     -*- lisp -*-
;;; How much I give a shit points
((version 11)
 ("title")
 ("content")
 ("title-or-content"
  ;; HIGH SCORE (1000-2000)
  (:text "advisory" :title-value 2000 :content-value 2000 :type W)
  (:text "judas release" :title-value 2000 :content-value 2000 :type W)
  (:text "bioshock release" :title-value 1800 :content-value 1800 :type W)
  (:text "cosmic desktop" :title-value 1800 :content-value 1800 :type W)
  (:text "judas" :title-value 1200 :content-value 1200 :type W)
  (:text "ghost story" :title-value 1200 :content-value 1200 :type W)
  (:text "fallout" :title-value 1000 :content-value 1000 :type W)
  (:text "doom" :title-value 1000 :content-value 1000 :type W)
  (:text "elder scrolls 6" :title-value 1000 :content-value 1000 :type W)
  (:text "media molecule" :title-value 800 :content-value 800 :type W)
  (:text "magit release" :title-value 700 :content-value 700 :type W)

  ;; MID SCORE (300-700)
  (:text "halifax election" :title-value 600 :content-value 600 :type W)
  (:text "starship" :title-value 600 :content-value 600 :type W)
  (:text "mars" :title-value 600 :content-value 600 :type W)
  (:text "nova scotia election" :title-value 500 :content-value 500 :type W)
  (:text "education" :title-value 400 :content-value 400 :type W)
  (:text "housing" :title-value 300 :content-value 300 :type W)
  (:text "healthcare" :title-value 300 :content-value 300 :type W)
  (:text "climate change" :title-value 300 :content-value 300 :type W)
  (:text "job market" :title-value 300 :content-value 300 :type W)

  ;; LOW SCORE (50-250)
  (:text "nova scotia" :title-value 250 :content-value 250 :type W)
  (:text "ai" :title-value 200 :content-value 200 :type W)
  (:text "relationship" :title-value 100 :content-value 100 :type W)
  (:text "child care" :title-value 100 :content-value 100 :type W)
  (:text "bioshock" :title-value 250 :content-value 250 :type W)
  (:text "interoperability" :title-value 100 :content-value 100 :type W)
  (:text "zero-Knowledge proofs" :title-value 100 :content-value 100 :type W)
  (:text "decentralized identity" :title-value 100 :content-value 100 :type W)
  (:text "decentralized governance" :title-value 100 :content-value 100 :type W)
  (:text "artificial general intelligence" :title-value 100 :content-value 100 :type W)

  ;; MICRO SCORE (50-99)
  (:text "halifax" :title-value 99 :content-value 99 :type W)
  (:text "innovation" :title-value 99 :content-value 99 :type W)
  (:text "emissions targets" :title-value 75 :content-value 75 :type W)
  (:text "launch" :title-value 75 :content-value 75 :type W)
  (:text "milestone" :title-value 75 :content-value 75 :type W)

  ;; Stuff I don't need to hear about (-500 to -2500)
  (:text "woke culture" :title-value -2500 :content-value -2500 :type W)
  (:text "cancel culture" :title-value -2500 :content-value -2500 :type W)
  (:text "virtue signaling" :title-value -2000 :content-value -2000 :type W)
  (:text "culture wars" :title-value -2000 :content-value -2000 :type W)
  (:text "tokenism" :title-value -1500 :content-value -1500 :type W)
  (:text "trans" :title-value -1000 :content-value -1000 :type W)
  )
 ("tag")
 ("authors"
  (:text "Ken Levine" :value 2000 :type s)
  (:text "Todd Howard" :value 1000 :type s)
  (:text "Hideo Kojima" :value 800 :type s))
 ("feed"
  (:text "Hyperledger" :value 500 :type S :attr t)
  (:text "NASA Blog" :value 500 :type S :attr t)
  (:text "GameInformer" :value 500 :type S :attr t))
 ("adjust-tags"))
